# permissions for end users to edit player-stats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: player-stats-editor-role
rules:
- apiGroups:
  - charts.quay.io
  resources:
  - player-stats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.quay.io
  resources:
  - player-stats/status
  verbs:
  - get
