# permissions for end users to view player-stats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: player-stats-viewer-role
rules:
- apiGroups:
  - charts.quay.io
  resources:
  - player-stats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.quay.io
  resources:
  - player-stats/status
  verbs:
  - get
